name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker images
      - name: Build and push Docker images
        run: |
          docker build -t flask-app .
          docker build -t nginx -f nginx/Dockerfile ./nginx

      # Step 4: Copy files to EC2
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "."
          target: "/home/ec2-user/flask-nginx"

      # Step 5: SSH into EC2 and run Docker Compose
      - name: Run Docker Compose on EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/flask-nginx
            sudo docker-compose down
            sudo docker-compose up -d
